# Generated by Django 5.1.7 on 2025-04-01 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OquvMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=255)),
                ('material_nomi', models.CharField(max_length=255)),
                ('tur', models.CharField(choices=[('kitob', 'Kitob'), ('video', 'Video dars'), ('qollanma', "Qo'llanma"), ('maqola', 'Maqola'), ('boshqa', 'Boshqa')], default='kitob', max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('mp4', 'MP4'), ('ppt', 'PPT'), ('doc', 'DOC'), ('boshqa', 'Boshqa')], default='pdf', max_length=50)),
                ('hajm', models.CharField(max_length=50)),
                ('yuklab_olish_imkoniyati', models.BooleanField(default=True)),
                ('status', models.CharField(default='Faol', max_length=50)),
                ('yuklangan_sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('hudud', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('yonalishlar', models.TextField(blank=True, null=True)),
                ('kirish_ballari', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('tur', models.CharField(choices=[('umumiy', 'Umumiy'), ('testlar', 'Testlar'), ('streak', 'Streak'), ('mock_testlar', 'Mock Testlar')], default='umumiy', max_length=20)),
                ('ball', models.IntegerField(default=0)),
                ('shart', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='yutuqlar/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('study_place', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IELTSUmumiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joriy_baho', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('maqsad_baho', models.DecimalField(decimal_places=1, default=7.5, max_digits=3)),
                ('listening', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reading', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('writing', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('speaking', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('keyingi_imtihon_sanasi', models.DateField(blank=True, null=True)),
                ('umumiy_progress', models.IntegerField(default=0)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_umumiy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IELTSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('til', models.CharField(choices=[('ingliz', 'Ingliz tili'), ('turk', 'Turk tili'), ('arab', 'Arab tili')], default='ingliz', max_length=20)),
                ('baho', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('sana', models.DateField(auto_now_add=True)),
                ('ielts_umumiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_testlar', to='users.ieltsumumiy')),
            ],
        ),
        migrations.CreateModel(
            name='IELTSMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='ielts_materiallar/')),
                ('yuklangan_sana', models.DateField(auto_now_add=True)),
                ('ielts_umumiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_materiallar', to='users.ieltsumumiy')),
            ],
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_ball', models.IntegerField(default=0)),
                ('testlar_ball', models.IntegerField(default=0)),
                ('kurslar_ball', models.IntegerField(default=0)),
                ('platforma_vaqti_ball', models.IntegerField(default=0)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinglar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fan', models.CharField(max_length=255)),
                ('savol_soni', models.IntegerField(default=0)),
                ('qiyinlik', models.CharField(max_length=50)),
                ('narx', models.IntegerField(default=0)),
                ('mukofot', models.IntegerField(default=0)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('vaqt_chegarasi', models.IntegerField(default=60)),
                ('qoshilgan_sana', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Faol', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol_matni', models.TextField()),
                ('qiyinlik', models.CharField(choices=[('oson', 'Oson'), ('orta', "O'rta"), ('qiyin', 'Qiyin'), ('murakkab', 'Murakkab')], default='oson', max_length=10)),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='users.test')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tavsif', models.CharField(max_length=255)),
                ('tur', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], default='kirim', max_length=10)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('muvaffaqiyatli', 'Muvaffaqiyatli'), ('bekor_qilingan', 'Bekor qilingan'), ('kutilmoqda', 'Kutilmoqda')], default='muvaffaqiyatli', max_length=20)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoydalanuvchiYutugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchi_yutuqlari', to=settings.AUTH_USER_MODEL)),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilar', to='users.yutuq')),
            ],
        ),
    ]
