# Generated by Django 5.1.7 on 2025-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
