# Generated by Django 5.1.7 on 2025-04-03 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test_is_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('davomiyligi', models.CharField(max_length=50)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
