# Generated by Django 5.1.7 on 2025-04-03 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=20)),
                ('fan', models.CharField(max_length=255)),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
                ('tur', models.CharField(max_length=50)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
