# Generated by Django 5.1.7 on 2025-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jadval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reyting',
            name='fizika_reyting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reyting',
            name='ingliz_tili_reyting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reyting',
            name='matematika_reyting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('superadmin', 'SuperAdmin')], default='student', max_length=10),
        ),
    ]
