# Generated by Django 5.1.7 on 2025-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreetoterms',
            field=models.BooleanField(default=False),
        ),
    ]
